[project]
name = "house-pricing-estimator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Giddy Garcia", email = "giddygarcia@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.1",
    "joblib>=1.6.0",
    "jupyter>=1.1.1",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "optuna>=5.0.0",
    "pandas>=3.0.6",
    "plotly>=7.1.0",
    "pydantic>=2.13.5",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "statsmodels>=0.15.0",
    "uvicorn>=0.54.0",
    "xgboost>=3.4.1",
]

[project.scripts]
house-pricing-estimator = "house_pricing_estimator:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
